MarketplaceCatalog/CQRSWeb/Controllers/HomeController.cs
using CQRSCode.ReadModel;
using CQRSCode.WriteModel.Commands;
using CQRSCode.ReadModel.Repository;
using CQRSlite.Commands;
using CQRSCode.ReadModel.Dtos;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CQRSWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICommandSender _commandSender;
        private readonly IRepository<ProductDto> _productsRepository;

        public HomeController(ICommandSender commandSender, IRepository<ProductDto> productsRepository)
        {
            _productsRepository = productsRepository;
            _commandSender = commandSender;
        }

        public ActionResult Index()
        {
            //ViewData.Model = _readmodel.GetInventoryItems();
            return View();
        }

        // public ActionResult Details(Guid id)
        // {
        //     ViewData.Model = _readmodel.GetInventoryItemDetails(id);
        //     return View();
        // }

        // public ActionResult Add()
        // {
        //     return View();
        // }

        // [HttpPost]
        // public ActionResult Add(string name)
        // {
        //     _commandSender.Send(new CreateInventoryItem(Guid.NewGuid(), name));
        //     return RedirectToAction("Index");
        // }

        // public ActionResult ChangeName(Guid id)
        // {
        //     ViewData.Model = _readmodel.GetInventoryItemDetails(id);
        //     return View();
        // }

        // [HttpPost]
        // public ActionResult ChangeName(Guid id, string name, int version)
        // {
        //     _commandSender.Send(new RenameInventoryItem(id, name, version));
        //     return RedirectToAction("Index");
        // }

        // public ActionResult Deactivate(Guid id, int version)
        // {
        //     _commandSender.Send(new DeactivateInventoryItem(id, version));
        //     return RedirectToAction("Index");
        // }

        // public ActionResult CheckIn(Guid id)
        // {
        //     ViewData.Model = _readmodel.GetInventoryItemDetails(id);
        //     return View();
        // }

        // [HttpPost]
        // public ActionResult CheckIn(Guid id, int number, int version)
        // {
        //     _commandSender.Send(new CheckInItemsToInventory(id, number, version));
        //     return RedirectToAction("Index");
        // }

        // public ActionResult Remove(Guid id)
        // {
        //     ViewData.Model = _readmodel.GetInventoryItemDetails(id);
        //     return View();
        // }

        // [HttpPost]
        // public ActionResult Remove(Guid id, int number, int version)
        // {
        //     _commandSender.Send(new RemoveItemsFromInventory(id, number, version));
        //     return RedirectToAction("Index");
        // }
    }
}

MarketplaceCatalog/CQRSWeb/Controllers/MerchantsController.cs
using CQRSCode.ReadModel;
using CQRSCode.WriteModel.Commands;
using CQRSCode.ReadModel.Repository;
using CQRSlite.Commands;
using CQRSCode.ReadModel.Dtos;
using Microsoft.AspNetCore.Mvc;
using System;
using AutoMapper;

namespace CQRSWeb.Controllers
{
    public class MerchantsController : Controller
    {
        private readonly ICommandSender _commandSender;
        private readonly IRepository<MerchantDto> _merchantsRepository;
        private readonly IMapper _mapper;

        public MerchantsController(ICommandSender commandSender,
                                    IRepository<MerchantDto> merchantsRepository,
                                    IMapper mapper)
        {
            _merchantsRepository = merchantsRepository;
            _commandSender = commandSender;
            _mapper = mapper;
        }

        public ActionResult Index(Int32? startIndex, Int32? limit)
        {
            if (startIndex == null)
                startIndex = 0;

            if (limit == null)
                limit = 10;

            ViewData.Model = _merchantsRepository.SearchFor(p => true, startIndex, limit);

            return View();
        }

        public ActionResult Details(Guid id)
        {
            var mercDto = _merchantsRepository.GetById(id);
            ViewData.Model = _mapper.Map<MerchantDto, Models.Merchant>(mercDto);
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Models.Merchant newMerchant)
        {
            if (!ModelState.IsValid)
                return View();

            Guid newId = Guid.NewGuid();

            _commandSender.Send<CreateMerchant>(new CreateMerchant(newId, newMerchant.Name, newMerchant.Email, newMerchant.Commission));

            return RedirectToAction("Details", new { id = newId });
        }

        [HttpGet]
        public ActionResult Activate(Guid id, Int32 version)
        {
            _commandSender.Send<ActivateMerchant>(new ActivateMerchant(id, version));

            return RedirectToAction("Details", new { id = id });
        }

        [HttpGet]
        public ActionResult Deactivate(Guid id, Int32 version)
        {
            _commandSender.Send<DeactivateMerchant>(new DeactivateMerchant(id, version));            

            return RedirectToAction("Details", new { id = id });
        }
    }
}

MarketplaceCatalog/CQRSWeb/Controllers/ProductsController.cs
using CQRSCode.ReadModel;
using CQRSCode.WriteModel.Commands;
using CQRSCode.ReadModel.Repository;
using CQRSlite.Commands;
using CQRSCode.ReadModel.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using AutoMapper;
using System;

namespace CQRSWeb.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ICommandSender _commandSender;
        private readonly IRepository<ProductDto> _productsRepository;
        private readonly IRepository<ProductSummaryDto> _productsSummaryRepository;
        private readonly IRepository<MerchantDto> _merchantsRepository;
        private readonly IMapper _mapper;

        public ProductsController(ICommandSender commandSender,
                                    IRepository<ProductDto> productsRepository,
                                    IRepository<ProductSummaryDto> productsSummaryRepository,
                                    IRepository<MerchantDto> merchantsRepository,
                                    IMapper mapper)
        {
            _productsRepository = productsRepository;
            _productsSummaryRepository = productsSummaryRepository;
            _commandSender = commandSender;
            _merchantsRepository = merchantsRepository;
            _mapper = mapper;
        }

        public ActionResult Index(Int32? startIndex, Int32? limit)
        {
            if (startIndex == null)
                startIndex = 0;

            if (limit == null)
                limit = 10;

            ViewData.Model = _productsRepository.SearchFor(p => true, startIndex, limit);

            return View();
        }

        public ActionResult Details(Guid id)
        {
            ViewData.Model = _productsRepository.GetById(id);

            if (ViewData.Model == null)
                return RedirectToAction("Index");

            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Models.Product newProduct)
        {
            if (!ModelState.IsValid)
                return View();

            Guid newId = Guid.NewGuid();

            _commandSender.Send<CreateProduct>(new CreateProduct(newId, newProduct.Name, newProduct.Description, newProduct.EAN, newProduct.UPC));

            return RedirectToAction("Details", new { id = newId });
        }

        [HttpGet]
        public ActionResult AddOffer(Guid productId)
        {
            var prod = _productsRepository.GetById(productId);
            var merchants = _merchantsRepository.SearchFor(mDto => true);

            var offer = new Models.Offer { ProductId = prod.Id, ProductName = prod.Name };
            offer.Merchants = _mapper.Map<IList<MerchantDto>, IList<Models.Merchant>>(merchants);
            ViewData.Model = offer;

            return View();
        }

        [HttpPost]
        public ActionResult AddOffer(Models.Offer newOffer)
        {
            if (!ModelState.IsValid)
                return View(newOffer);

            Guid newId = Guid.NewGuid();

            _commandSender.Send<CreateOffer>(
                    new CreateOffer(
                        newId, newOffer.ProductId, newOffer.MerchantId,
                        newOffer.Price, newOffer.Stock, newOffer.SKU
                      ));

            return RedirectToAction("Details", new { id = newOffer.ProductId });
        }
    }
}

MarketplaceCatalog/CQRSWeb/Views/Home/Add.cshtml
@{
    ViewData["Title"] = "Add";
}
<h2>Add</h2>
@using (Html.BeginForm()) {
    <p>
        Name: @Html.TextBox("Name")<br />
        <button name="submit">Submit</button>
        <a href="/">Back</a>
    </p>

}

MarketplaceCatalog/CQRSWeb/Views/Home/ChangeName.cshtml
@model CQRSCode.ReadModel.Dtos.InventoryItemDetailsDto
@{
    ViewData["Title"] = "ChangeName";
}
<h2>ChangeName</h2>
@using (Html.BeginForm())
{
    <p>
        @Html.Hidden("Id", Model.Id)
        @Html.Hidden("Version", Model.Version)
        Name: @Html.TextBox("Name")<br />
        <button name="submit">Submit</button>
        <a href="/">Back</a>
    </p>
}
    

MarketplaceCatalog/CQRSWeb/Views/Home/CheckIn.cshtml
@model CQRSCode.ReadModel.Dtos.InventoryItemDetailsDto
@{
    ViewData["Title"] = "CheckIn";
}

<h2>CheckIn</h2>
@using (Html.BeginForm())
{
    <p>
        @Html.Hidden("Id",Model.Id)
        @Html.Hidden("Version",Model.Version)
        Number: @Html.TextBox("Number")<br />
        <button name="submit">Submit</button>
        <a href="/">Back</a>
    </p>
}

MarketplaceCatalog/CQRSWeb/Views/Home/Details.cshtml
@model CQRSCode.ReadModel.Dtos.InventoryItemDetailsDto
@{
    ViewData["Title"] = "Details";
}
<h2>Details:</h2>
Id: @Model.Id<br />
Name: @Model.Name<br />
Count: @Model.CurrentCount<br /><br />

@Html.ActionLink("Rename","ChangeName", new{Id=Model.Id})<br />
@Html.ActionLink("Deactivate","Deactivate",new{Id=Model.Id, Version = Model.Version})<br />
@Html.ActionLink("Check in","CheckIn", new{Id=Model.Id})<br />
@Html.ActionLink("Remove","Remove", new{Id=Model.Id,Version=Model.Version})<br /><br />
<a href="/">Back</a>

MarketplaceCatalog/CQRSWeb/Views/Home/Index.cshtml
@*@model IEnumerable<CQRSCode.ReadModel.Dtos.InventoryItemListDto>*@
@{
    ViewData["Title"] = "Home Page";
}

@Html.ActionLink("View products", "Index", "Products")<br />
@Html.ActionLink("View merchants", "Index", "Merchants")

@*@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>*@

MarketplaceCatalog/CQRSWeb/Views/Home/Remove.cshtml
@model CQRSCode.ReadModel.Dtos.InventoryItemDetailsDto
@{
    ViewData["Title"] = "Remove";
}

<h2>Remove</h2>
@using (Html.BeginForm())
{
    <p>
        @Html.Hidden("Id",Model.Id)
        @Html.Hidden("Version",Model.Version)
        Number: @Html.TextBox("Number")<br />
        <button name="submit">Submit</button>         
        <a href="/">Back</a>
    </p>
}